-- MySQL Script generated by MySQL Workbench
-- Wed Jul  7 20:23:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bonita
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bonita
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bonita` DEFAULT CHARACTER SET utf8 ;
USE `Bonita` ;

-- -----------------------------------------------------
-- Table `Bonita`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bonita`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bonita`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bonita`.`Staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bonita`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bonita`.`Service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `price` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bonita`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bonita`.`Appointment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `User_id` INT NOT NULL,
  `Service_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
